name: frontend
language: nodejs
variables:
  - name: API_URL
    inputType: FreeText
    description: Backend API URL for server-side requests (internal Kubernetes service name)
    defaultValue: http://test-manager-backend
    required: true
  - name: NODE_ENV
    inputType: FreeText
    description: Node environment
    defaultValue: production
    required: true
  - name: NEXT_TELEMETRY_DISABLED
    inputType: FreeText
    description: Disable Next.js telemetry
    defaultValue: 1
  - name: MEASUREMENTS_URL
    inputType: FreeText
    multiline: false
    defaultValue: https://query-ui-quixers-testrigdemodatawarehouse-prod.az-france-0.app.quix.io/
    required: true
dockerfile: dockerfile
runEntryPoint: package.json
defaultFile: package.json
